//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liga
    {
        public Liga()
        {
            this.Team = new HashSet<Team>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int IdTorneo { get; set; }
    
        public virtual Torneo Torneo { get; set; }
        public virtual ICollection<Team> Team { get; set; }
    }
}
