//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Player = new HashSet<Player>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int IdLiga { get; set; }
    
        public virtual Liga Liga { get; set; }
        public virtual ICollection<Player> Player { get; set; }
    }
}
