//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Liga = new HashSet<Liga>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int IdPlayer { get; set; }
    
        public virtual ICollection<Liga> Liga { get; set; }
        public virtual Player Player { get; set; }
    }
}
